{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kshitij.typestring",
    "module": "typestring-annotations",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-annotations-metadata-0.5.0.jar",
          "url": "typestring-annotations-0.5.0.jar",
          "size": 2872,
          "sha512": "5fb0f960a6f79c9fc7975227685aeea014f53ab84c150f32f04c33db563a14f10e3817af6982d08e6da27515f5ead5d6c9ab0da06582d7c6a8cad0e3a8985d29",
          "sha256": "d78439d19786b60661afec7a2ee317d57be8a97594fa07acdeca12b2a374dd40",
          "sha1": "983787a1510c0ba34264572dbde77bfd019aeb1e",
          "md5": "bc72616c2bc2667be9448ff27b38920c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "typestring-annotations-kotlin-0.5.0-sources.jar",
          "url": "typestring-annotations-0.5.0-sources.jar",
          "size": 1563,
          "sha512": "6b4198589efe461a37b857f9f72934a44b44e22d815c92a5c474e7008739618270b310664df3ed9907573a2c86400c2e6d13d92631e7884c8d112ceba79198d1",
          "sha256": "2685352750c10eda9268c571933d69b6e59d18b89d3b5800253db6122adcadb5",
          "sha1": "05f5c16aa4cd0febbf15695b0701418da7682205",
          "md5": "f1fba956e31af0476abf3741cf111bed"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../typestring-annotations-android/0.5.0/typestring-annotations-android-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../typestring-annotations-android/0.5.0/typestring-annotations-android-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../typestring-annotations-android/0.5.0/typestring-annotations-android-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosarm64/0.5.0/typestring-annotations-iosarm64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosarm64/0.5.0/typestring-annotations-iosarm64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosarm64/0.5.0/typestring-annotations-iosarm64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iossimulatorarm64/0.5.0/typestring-annotations-iossimulatorarm64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iossimulatorarm64/0.5.0/typestring-annotations-iossimulatorarm64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iossimulatorarm64/0.5.0/typestring-annotations-iossimulatorarm64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosx64/0.5.0/typestring-annotations-iosx64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosx64/0.5.0/typestring-annotations-iosx64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosx64/0.5.0/typestring-annotations-iosx64-0.5.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosx64",
        "version": "0.5.0"
      }
    }
  ]
}
