{
  "formatVersion": "1.1",
  "component": {
    "url": "../../typestring-annotations/0.5.0/typestring-annotations-0.5.0.module",
    "group": "io.kshitij.typestring",
    "module": "typestring-annotations",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-annotations.aar",
          "url": "typestring-annotations-android-0.5.0.aar",
          "size": 1976,
          "sha512": "59389d399c5b4aa8e3b785f7c2acb429273571732b499ef897cb47262ad04f090dceb212343bab4a5c85587d724d57717f4b23ab23ca4df9e782dc325c923ed2",
          "sha256": "b81741d7e6d670b92cf6c5222194337c5bcf39f59f75ac33794719cf2d7b486d",
          "sha1": "29108f014b90820f25653d03efd96a89ce02614b",
          "md5": "92b1833489ddd447da1ad182c7b888cc"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-annotations.aar",
          "url": "typestring-annotations-android-0.5.0.aar",
          "size": 1976,
          "sha512": "59389d399c5b4aa8e3b785f7c2acb429273571732b499ef897cb47262ad04f090dceb212343bab4a5c85587d724d57717f4b23ab23ca4df9e782dc325c923ed2",
          "sha256": "b81741d7e6d670b92cf6c5222194337c5bcf39f59f75ac33794719cf2d7b486d",
          "sha1": "29108f014b90820f25653d03efd96a89ce02614b",
          "md5": "92b1833489ddd447da1ad182c7b888cc"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "typestring-annotations-android-0.5.0-sources.jar",
          "url": "typestring-annotations-android-0.5.0-sources.jar",
          "size": 1563,
          "sha512": "6b4198589efe461a37b857f9f72934a44b44e22d815c92a5c474e7008739618270b310664df3ed9907573a2c86400c2e6d13d92631e7884c8d112ceba79198d1",
          "sha256": "2685352750c10eda9268c571933d69b6e59d18b89d3b5800253db6122adcadb5",
          "sha1": "05f5c16aa4cd0febbf15695b0701418da7682205",
          "md5": "f1fba956e31af0476abf3741cf111bed"
        }
      ]
    }
  ]
}
