{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kshitij.typestring",
    "module": "typestring-processor",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-processor-0.1.0.jar",
          "url": "typestring-processor-0.1.0.jar",
          "size": 12057,
          "sha512": "62c7f60d2a10aaa43b82c86b4402252bb279139f20276533d93a3ebbc306a4c1b8e1c04048e4e4b4ed4d1b5c0e79ec43d35102963901603631b65e8df4e9420c",
          "sha256": "0ba238a31cc42ff15893bedface918ba4dd0d6d8d3282e4fee5f97ee821ed728",
          "sha1": "6411a1c64112820cf1ad3a486ec5d40bdb612a0e",
          "md5": "8f31e8f347b67aa704e52715efeb07cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-processor-0.1.0.jar",
          "url": "typestring-processor-0.1.0.jar",
          "size": 12057,
          "sha512": "62c7f60d2a10aaa43b82c86b4402252bb279139f20276533d93a3ebbc306a4c1b8e1c04048e4e4b4ed4d1b5c0e79ec43d35102963901603631b65e8df4e9420c",
          "sha256": "0ba238a31cc42ff15893bedface918ba4dd0d6d8d3282e4fee5f97ee821ed728",
          "sha1": "6411a1c64112820cf1ad3a486ec5d40bdb612a0e",
          "md5": "8f31e8f347b67aa704e52715efeb07cc"
        }
      ]
    }
  ]
}
