{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kshitij.typestring",
    "module": "typestring-processor",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-processor-0.2.0.jar",
          "url": "typestring-processor-0.2.0.jar",
          "size": 11956,
          "sha512": "6c5fec3ed5bc00eee8e4b7d97675ab0b2db29407fa62cbd56d1be7e1b634329332978c2edbc6066e2a1f9abcda88ed096ed3d926d4bd787329d65e3a1e34ebcb",
          "sha256": "a3cb5ee801e7d6916073d022ed657b3bc948458792d872c376d9dfe3bf52d5e3",
          "sha1": "336bb9bcbfeb7b70d72c1511720a863b9e599ef1",
          "md5": "94f4318bdd3e079523476f5559417c51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-processor-0.2.0.jar",
          "url": "typestring-processor-0.2.0.jar",
          "size": 11956,
          "sha512": "6c5fec3ed5bc00eee8e4b7d97675ab0b2db29407fa62cbd56d1be7e1b634329332978c2edbc6066e2a1f9abcda88ed096ed3d926d4bd787329d65e3a1e34ebcb",
          "sha256": "a3cb5ee801e7d6916073d022ed657b3bc948458792d872c376d9dfe3bf52d5e3",
          "sha1": "336bb9bcbfeb7b70d72c1511720a863b9e599ef1",
          "md5": "94f4318bdd3e079523476f5559417c51"
        }
      ]
    }
  ]
}
