{
  "formatVersion": "1.1",
  "component": {
    "url": "../../typestring-annotations/0.3.0/typestring-annotations-0.3.0.module",
    "group": "io.kshitij.typestring",
    "module": "typestring-annotations",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-annotations.aar",
          "url": "typestring-annotations-android-0.3.0.aar",
          "size": 1487,
          "sha512": "3ac088b1a42f6fcfb05d3ca13215d44cef17bd9262ac54fdd4da7a7993d7cf00518ffbd101f6c137bb32c79865ce03a03c8c978649cad1cef81f54622ad9ae07",
          "sha256": "892c56c970edf4cf104f8637c2bb66ca85bc19aff14f60c20624899c533a4b2f",
          "sha1": "930420f862cae0ffc11798b72ba2ff5b2218cb6c",
          "md5": "3dd46c5823be626c4e879f34359089d4"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-annotations.aar",
          "url": "typestring-annotations-android-0.3.0.aar",
          "size": 1487,
          "sha512": "3ac088b1a42f6fcfb05d3ca13215d44cef17bd9262ac54fdd4da7a7993d7cf00518ffbd101f6c137bb32c79865ce03a03c8c978649cad1cef81f54622ad9ae07",
          "sha256": "892c56c970edf4cf104f8637c2bb66ca85bc19aff14f60c20624899c533a4b2f",
          "sha1": "930420f862cae0ffc11798b72ba2ff5b2218cb6c",
          "md5": "3dd46c5823be626c4e879f34359089d4"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "typestring-annotations-android-0.3.0-sources.jar",
          "url": "typestring-annotations-android-0.3.0-sources.jar",
          "size": 1021,
          "sha512": "77dfad63e644a9809dd1b76a712c28d6a664bfaf3b79d2fd0a5173aeffeec59d0530712305234ed1bfb675465d73c7cd7b1c28f709c3ffc120a16724337ebcf8",
          "sha256": "aff85163c17aceb75f5d027d645a7fdbe12f2b482aa604cad422852d436ee8fe",
          "sha1": "1ce71c0a0f0d3a6dce8075d45ca37c71c60c12ab",
          "md5": "6d3d534e77fa3eeb13b93be87bf8ea50"
        }
      ]
    }
  ]
}
