{
  "formatVersion": "1.1",
  "component": {
    "group": "io.kshitij.typestring",
    "module": "typestring-annotations",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-annotations-metadata-0.3.0.jar",
          "url": "typestring-annotations-0.3.0.jar",
          "size": 2398,
          "sha512": "a135d382c86e52636e2ffd8a2ae44a597eeb430ec808449dff33460ae6b9934da52b5a60500fa421050a5732df34b0247db16b1ea6ade20f3cf4cd4dbc225af3",
          "sha256": "fc0134f961ce7916e4e379eb5b714b165f2154a9c12502a1b09d08e3f29e974b",
          "sha1": "2c2528d13814ab9a33c2e37862245aec15bc5207",
          "md5": "3397a96cce988bcc4cb33d0bd3835e99"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "typestring-annotations-kotlin-0.3.0-sources.jar",
          "url": "typestring-annotations-0.3.0-sources.jar",
          "size": 1021,
          "sha512": "77dfad63e644a9809dd1b76a712c28d6a664bfaf3b79d2fd0a5173aeffeec59d0530712305234ed1bfb675465d73c7cd7b1c28f709c3ffc120a16724337ebcf8",
          "sha256": "aff85163c17aceb75f5d027d645a7fdbe12f2b482aa604cad422852d436ee8fe",
          "sha1": "1ce71c0a0f0d3a6dce8075d45ca37c71c60c12ab",
          "md5": "6d3d534e77fa3eeb13b93be87bf8ea50"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../typestring-annotations-android/0.3.0/typestring-annotations-android-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-android",
        "version": "0.3.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../typestring-annotations-android/0.3.0/typestring-annotations-android-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-android",
        "version": "0.3.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../typestring-annotations-android/0.3.0/typestring-annotations-android-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-android",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosarm64/0.3.0/typestring-annotations-iosarm64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosarm64/0.3.0/typestring-annotations-iosarm64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosarm64/0.3.0/typestring-annotations-iosarm64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iossimulatorarm64/0.3.0/typestring-annotations-iossimulatorarm64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iossimulatorarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iossimulatorarm64/0.3.0/typestring-annotations-iossimulatorarm64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iossimulatorarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iossimulatorarm64/0.3.0/typestring-annotations-iossimulatorarm64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iossimulatorarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosx64/0.3.0/typestring-annotations-iosx64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosx64/0.3.0/typestring-annotations-iosx64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../typestring-annotations-iosx64/0.3.0/typestring-annotations-iosx64-0.3.0.module",
        "group": "io.kshitij.typestring",
        "module": "typestring-annotations-iosx64",
        "version": "0.3.0"
      }
    }
  ]
}
