{
  "formatVersion": "1.1",
  "component": {
    "url": "../../typestring-annotations/0.1.0/typestring-annotations-0.1.0.module",
    "group": "io.kshitij.typestring",
    "module": "typestring-annotations",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-annotations.aar",
          "url": "typestring-annotations-android-0.1.0.aar",
          "size": 1568,
          "sha512": "1df680ff9c4635528409545b9a1053b9852c7d38ca9ac02b31721be50a9224dee47c160046f25edfb6a7117e9062313beae28c70012f124dee3b8e68d51a28bd",
          "sha256": "e519f6dfa54cbc0fd37041a3e47a1eab46cd1f31fefd726bf3705c2b8e391aa9",
          "sha1": "5f855dec3fffbde6757788345fb0c52591761c0a",
          "md5": "e2857ab7f739507f6b44143515f57ea6"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "typestring-annotations.aar",
          "url": "typestring-annotations-android-0.1.0.aar",
          "size": 1568,
          "sha512": "1df680ff9c4635528409545b9a1053b9852c7d38ca9ac02b31721be50a9224dee47c160046f25edfb6a7117e9062313beae28c70012f124dee3b8e68d51a28bd",
          "sha256": "e519f6dfa54cbc0fd37041a3e47a1eab46cd1f31fefd726bf3705c2b8e391aa9",
          "sha1": "5f855dec3fffbde6757788345fb0c52591761c0a",
          "md5": "e2857ab7f739507f6b44143515f57ea6"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "typestring-annotations-android-0.1.0-sources.jar",
          "url": "typestring-annotations-android-0.1.0-sources.jar",
          "size": 1021,
          "sha512": "77dfad63e644a9809dd1b76a712c28d6a664bfaf3b79d2fd0a5173aeffeec59d0530712305234ed1bfb675465d73c7cd7b1c28f709c3ffc120a16724337ebcf8",
          "sha256": "aff85163c17aceb75f5d027d645a7fdbe12f2b482aa604cad422852d436ee8fe",
          "sha1": "1ce71c0a0f0d3a6dce8075d45ca37c71c60c12ab",
          "md5": "6d3d534e77fa3eeb13b93be87bf8ea50"
        }
      ]
    }
  ]
}
